// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bsqeddnaiojvvckpdvcu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzcWVkZG5haW9qdnZja3BkdmN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk5ODQ3MjEsImV4cCI6MjA4NTU2MDcyMX0.9WUEYU5PshM6UbJbKTogIXg8aIpaez_MfVW98EaionY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});